### PR TITLE
Sends POST request to Professor Bloom on new welcome (eventually will replace the message alltogether)

### PR DESCRIPTION
**Pull request by jaspermayone**

### CODE REVIEW

**Review by cskartikey — COMMENTED** [review]
wohooo. Can't wait to resume my work on professor bloom

**Comment by cskartikey** [comment]
Why was I able to review tho?

**Comment by jaspermayone** [comment]
@tregsthedev do you know what's causing this error? trying to resolve so i can get this merged and up and running.

**Comment by tregsthedev** [comment]
LGTM! merged

**Comment by jaspermayone** [comment]
We are reverting!

**Pull request merged**
