### PR TITLE
Add Toby Fox startup message

### PR DESCRIPTION
**Pull request by AverseABFun**

### CODE REVIEW

**Review by aboutdavid — APPROVED** [review]

**Review by tregsthedev — CHANGES_REQUESTED** [review]
I don't think this really fits in with the the other startup messages

**Comment by aboutdavid** [comment]
> I don't think this really fits in with the the other startup messages

There are some that say:
seeing the fish go "wahoo" 

Plus isn't toriel from undertale?

**Comment by tregsthedev** [comment]
seeing the fish go wahooo is an old internal HC joke :P.

**Comment by AverseABFun** [comment]
Exactly, Toriel is from undertale

**Comment by jaspermayone** [comment]
Echoing @tregsthedev, this doesn't really fit with Toriel's vibe.

@AverseABFun, feel free to PR some that fix more closely!

**Pull request closed without merging**
