### PR TITLE
Migrate to prisma 5

### PR DESCRIPTION
**Pull request by aboutdavid**
Did a bit of testing, toriel does in fact, not implode when upgraded to prisma 5

(or maybe toriel will in prod to make me look bad, idk)

### CODE REVIEW

**Comment by jaspermayone** [comment]
@maxwofford can you review this one plz? Just want to confirm its all good before merging.

**Comment by jaspermayone** [comment]
Hrmmmmmmm.... @aboutdavid can you throughly test once I merge to prod to make sure we haven't broken anything.

**Comment by aboutdavid** [comment]
Sure!

Prisma 4 and 5 hasn't implemented any major changes that affect us though

**Comment by jaspermayone** [comment]
@aboutdavid I am going to merge this, plz watch closely for a bit to make sure nothing breaks. (I'd suggest completely running through the flow with a new account)

**Review by jaspermayone — APPROVED** [review]

**Pull request merged**
