### PR TITLE
Remove node-fetch in favour of native API & format Prisma schema

### PR DESCRIPTION
**Pull request by aboutdavid**

### CODE REVIEW

**Review by jaspermayone — DISMISSED** [review]

**Comment by jaspermayone** [comment]
@aboutdavid merge conflicts

**Comment by tregsthedev** [comment]
oops

**Review by jaspermayone — APPROVED** [review]

**Comment by aboutdavid** [comment]
yarn.lock wasn't resolved properly, @prisma/client was removed

**Comment by jaspermayone** [comment]
ah dang it

**Pull request merged**
