### PR TITLE
Add Grafana logging

### PR DESCRIPTION
**Pull request by ShubhamPatilsd**
Added various logging that can be accessed via https://telemetry.hackclub.com through the toriel service

### CODE REVIEW

**Comment by jaspermayone** [comment]
@ShubhamPatilsd is this fully featured / ready for prod?

**Comment by aboutdavid** [comment]
I'll have to review it when I get home (lunch, then bus, then drive home)

**Comment by aboutdavid** [comment]
Working on this now

**Comment by aboutdavid** [comment]
Made a slight change: allowed `process.env.NODE_ENV` to be any case

**Review by aboutdavid — APPROVED** [review]
Tested everything, should be OK.

**Review by jaspermayone — APPROVED** [review]
LGTM @aboutdavid.

Plz monitor graf to see if this is working!

**Comment by jaspermayone** [comment]
YAY!

**Pull request merged**
